// Generated by CoffeeScript 1.9.3
(function() {
  module.exports.schema = function(db, models, next) {
    models.alarm = db.define("alarm", {
      id: Number,
      date: {
        type: 'date',
        time: true
      }
    });
    models.device = db.define('device', {
      id: Number,
      gateway: Number,
      uuid: String
    });
    models.gateway = db.define("gateway", {
      id: Number,
      name: String,
      identifier: String,
      online: Boolean
    });
    global.DB = models;
    db.sync();
    return next();
  };

}).call(this);

//# sourceMappingURL=databaseSchema.js.map
